[tool.poetry]
name = "cmp"
version = "0.1.0"
description = ""
authors = ["dany"]

[tool.poetry.dependencies]
python = "3.8.5"
pytest = "^6.2.2"
pytest-ordering = "^0.6"
sly = "^0.4"
ply = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
